# Generated by Django 5.1.1 on 2024-10-01 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('пылесос', 'Пылесос'), ('холодильник', 'Холодильник'), ('утюг', 'Утюг'), ('морозильник', 'Морозильник'), ('телевизор', 'Телевизор'), ('аристон', 'Аристон'), ('вафельница', 'Вафельница'), ('блендер', 'Блендер'), ('миксер', 'Миксер'), ('вытяжка', 'Вытяжка'), ('стиральная_машина', 'Стиральная машина'), ('кондиционер', 'Кондиционер')], max_length=50, unique=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('specifications', models.TextField(blank=True, verbose_name='Характеристики')),
                ('store_name', models.CharField(blank=True, max_length=255, verbose_name='Магазин')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
