# Generated by Django 5.1.1 on 2024-10-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Названия магазин')),
                ('address', models.CharField(max_length=255, verbose_name='Адресс')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('whatsapp_number', models.CharField(max_length=20, verbose_name='Ватсап Номер')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Адресс вашего сайта')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='Instagram ссылка')),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='Facebook ссылка')),
                ('start_time', models.TimeField(verbose_name='Начало работы')),
                ('end_time', models.TimeField(verbose_name='Окончание работы')),
                ('personal_courier', models.BooleanField(default=False, verbose_name='Личный Курьер')),
                ('round_the_clock', models.BooleanField(default=False, verbose_name='Кругло Суточно')),
                ('shop_description', models.TextField(blank=True, null=True, verbose_name='Описание Магазин')),
                ('payment_methods', models.CharField(max_length=255, verbose_name='Оплата')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_images/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
    ]
